# Generated by Django 2.2 on 2019-06-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userGender', models.CharField(max_length=45)),
                ('perfilPro', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=45)),
                ('adress', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('userLastname', models.CharField(max_length=255)),
                ('UserEmail', models.CharField(max_length=255)),
                ('userPass', models.CharField(max_length=255)),
                ('userStatus', models.CharField(max_length=45)),
            ],
        ),
    ]
